### ISSUE TITLE
TypeError: runner.metro.getBundler(...).getBundler(...).getWatcher is not a function

### ISSUE THREAD

**Issue by martnst** [Tmeister/jwt-client#83]
Hey, thanks for providing this demo client along with your [JWT Authentication for WP REST API](https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api) wordpress plugin. 

Unf. fails to start with the following error: 

```
➜  jwt-client git:(main) ✗ npm run ios  

> jwt-client@1.0.0 ios
> expo start --ios

Starting project at /Users/martin/Projects/hellomed/Development/jwt-client
● Validation Warning:

  Unknown option "watcher" with value {"additionalExts": ["env.development.local", "env.local", "env.development", "env"]} was found.
  This is probably a typing mistake. Fixing it will remove this message.

Starting Metro Bundler
TypeError: runner.metro.getBundler(...).getBundler(...).getWatcher is not a function
TypeError: runner.metro.getBundler(...).getBundler(...).getWatcher is not a function
    at Object.observeFileChanges (/Users/martin/Projects/hellomed/Development/jwt-client/node_modules/@expo/cli/build/src/start/server/metro/waitForMetroToObserveTypeScriptFile.js:44:60)
    at MetroBundlerDevServer.watchEnvironmentVariables (/Users/martin/Projects/hellomed/Development/jwt-client/node_modules/@expo/cli/build/src/start/server/metro/MetroBundlerDevServer.js:209:51)
    at DevServerManager.watchEnvironmentVariables (/Users/martin/Projects/hellomed/Development/jwt-client/node_modules/@expo/cli/build/src/start/server/DevServerManager.js:192:35)
    at startAsync (/Users/martin/Projects/hellomed/Development/jwt-client/node_modules/@expo/cli/build/src/start/startAsync.js:127:32)
```

**Comment by martnst** [comment]
Ah sorry… my fault… kinda. 

After running `npm install` it suggested to fix vulnerabilities by running `npm audit fix`, which i did. 

Starting over by with a clean `npm install` it's working now.
